# Generated by Django 3.2.7 on 2021-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageFile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
