# Generated by Django 3.2.7 on 2021-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='videoFile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
