# Generated by Django 3.2.7 on 2021-09-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageFile',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
